# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkynxCli < Formula
  desc "skynx-cli"
  homepage "https://skynx.com"
  version "0.0.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/skynx-io/s-cli/releases/download/v0.0.0/skynx-cli_0.0.0_darwin_amd64.tar.gz"
      sha256 "5ab9571618f67abf58d48565053d448560ce903cb282e7f7a19ea8560a167857"

      def install
        bin.install "skynxctl"
        bash_completion.install "completions/skynxctl.bash" => "skynxctl"
        zsh_completion.install "completions/skynxctl.zsh" => "_skynxctl"
        fish_completion.install "completions/skynxctl.fish"
      end
    end
    on_arm do
      url "https://github.com/skynx-io/s-cli/releases/download/v0.0.0/skynx-cli_0.0.0_darwin_arm64.tar.gz"
      sha256 "00b40f1132333a610a66e75a5b2a4a797b69e2d75c7555d14bd8eb800ddc75ae"

      def install
        bin.install "skynxctl"
        bash_completion.install "completions/skynxctl.bash" => "skynxctl"
        zsh_completion.install "completions/skynxctl.zsh" => "_skynxctl"
        fish_completion.install "completions/skynxctl.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skynx-io/s-cli/releases/download/v0.0.0/skynx-cli_0.0.0_linux_amd64.tar.gz"
        sha256 "75f04cff433b64525762452d4970ba78eb49d240833829e6c83adf2f817bc893"

        def install
          bin.install "skynxctl"
          bash_completion.install "completions/skynxctl.bash" => "skynxctl"
          zsh_completion.install "completions/skynxctl.zsh" => "_skynxctl"
          fish_completion.install "completions/skynxctl.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skynx-io/s-cli/releases/download/v0.0.0/skynx-cli_0.0.0_linux_arm64.tar.gz"
        sha256 "93eb28137b4c261e23d68e66edc55c79c551715355a0b8e6c2e8c0ac8c7150b1"

        def install
          bin.install "skynxctl"
          bash_completion.install "completions/skynxctl.bash" => "skynxctl"
          zsh_completion.install "completions/skynxctl.zsh" => "_skynxctl"
          fish_completion.install "completions/skynxctl.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/skynxctl version show"
  end
end
