# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkynxNode < Formula
  desc "skynx-node agent"
  homepage "https://skynx.com"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/skynx-io/s-node/releases/download/v0.0.1/skynx-node_0.0.1_darwin_amd64.tar.gz"
      sha256 "de668f686cd8a294a7408a2aedc6106772dd34d05d45a83cff62c5d0901d6ed2"

      def install
        libexec.install "skynx-node"
      end
    end
    on_arm do
      url "https://github.com/skynx-io/s-node/releases/download/v0.0.1/skynx-node_0.0.1_darwin_arm64.tar.gz"
      sha256 "a1558a3a3bbed705f33a5b7cefe9f06f0c914f763f73094c2ed1cc333f50973a"

      def install
        libexec.install "skynx-node"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skynx-io/s-node/releases/download/v0.0.1/skynx-node_0.0.1_linux_amd64.tar.gz"
        sha256 "0de760697423fc1cb069c9502d8106212900a6b541b6f2c72bf24aa21f19ebec"

        def install
          libexec.install "skynx-node"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/skynx-io/s-node/releases/download/v0.0.1/skynx-node_0.0.1_linux_arm64.tar.gz"
        sha256 "12cf7fa12bc8870e43a2f99a1926d465ff2bd13fa318cb473bd5eb3b681e16cf"

        def install
          libexec.install "skynx-node"
        end
      end
    end
  end

  test do
    system "#{libexec}/skynx-node version"
  end
end
